### ISSUE TITLE
Migrate to grpc-dotnet

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/zeebe-client-csharp#348]
**Is your feature request related to a problem? Please describe.**

https://grpc.io/blog/grpc-csharp-future/ 

> TL;DR grpc-dotnet (the Grpc.Net.Client and Grpc.AspNetCore.Server nuget packages) is now the recommended gRPC implementation for .NET/C#. The original gRPC C# implementation (the Grpc.Core nuget package) will enter maintenance mode and won’t be getting any new features and will only receive important bug fixes and security fixes going forward. The ultimate plan is to phase out Grpc.Core completely at some point in the future. This announcement describes the reasons why we have decided to do so and lays out the plan in more detail.

**Describe the solution you'd like**

* Migrate the internal backend to the https://github.com/grpc/grpc-dotnet without breaking the API. 
* We need to migrate the client to a higher .net version https://github.com/camunda-community-hub/zeebe-client-csharp/issues/277
* Release with this change a new major version

**Describe alternatives you've considered**

Stick with the grpc-core

**Additional context**

This would solve https://github.com/camunda-community-hub/zeebe-client-csharp/issues/194

**Comment by arjangeertsema** [comment]
Hey @Zelldon, it has been a long time since there has been a release of a new version. What is you policy regarding not falling to for behind software updates? 

My bootstrap project is highly dependent of your project and I would regret to see that it will be failing because of this.

For the time being could you add Apple M1 support to your project? (https://github.com/einari/Grpc.Core.M1) 

Hopefully you will be able to release a new version which will fix a lot of issues including this one.

Thanks!

Arjan

**Comment by Zelldon** [comment]
Tbh I was also thinking for a while to create a new release but always miss it. I try to do it soon. Please remind me if I miss it again

**Comment by Zelldon** [comment]
@arjangeertsema https://github.com/camunda-community-hub/zeebe-client-csharp/releases/tag/1.3

**Comment by jothikiruthika** [comment]
Hi @Zelldon, now that .net 3.1 has already reached EOL, developers naturally look forward to code with .net 6.0 & Above. But the zb-client library has an internal dependency on Grpc.core, this has to be migrated to [grpc-dotnet ](https://grpc.io/blog/grpc-csharp-future/) Without this support in the C# client, we are forced to stick to .net core 3.1 on the MAC, since [the native Grpc library in C# is not available for arm based images](https://grpc.io/blog/grpc-csharp-future/).

**Comment by xlegalles** [comment]
Can we help? (contribute)

**Comment by xomiamoore** [comment]
Hey @xlegalles, absolutely, contributions are welcome!

**Comment by xlegalles** [comment]
Ok, I've started to work on it and quickly found a problem: the keepAlive option is not supported by the new implementation
https://github.com/grpc/grpc-dotnet/blob/4c410dcc3942e8705602d63f03f8b6b8b9df8e72/doc/implementation_comparison.md#fine-grained-transport-control-keepalive
So it seems that the AddKeepAliveToChannelOptions method in ZeebeClient.cs cannot be supported anymore. But I don't know the consequences of this?

**Comment by xlegalles** [comment]
So the documentation is not up-to-date: found this [discussion ](https://github.com/grpc/grpc-dotnet/issues/770) about it with a solution.

**Comment by xlegalles** [comment]
I've pushed a PR. The pipeline needs to be updated as my branch targets net5.0, net6.0 and net7.0.
