### ISSUE TITLE
I can not use the client to connect to local/docker instance of the engine.

### ISSUE THREAD

**Issue by ShawnAbshire** [camunda-community-hub/zeebe-client-csharp#439]
**Is your feature request related to a problem? Please describe.**
Recently started working on building out a worker node and noticed that the forces port 443 for the contact point.  This is problematic whenever we're not using a cloud instance just yet, but instead are using the camunda provided [docker platform](https://github.com/camunda/camunda-platform/tree/8.0.0) which defaults the Zeebe engine port to 26500.

**Describe the solution you'd like**
I think adding an override to the `UseContactPoint` method with the ability to disable the usage of the SSL port, example:

Before:
` ICamundaCloudClientBuilderFinalStep UseContactPoint(string contactPoint);`

After:
` ICamundaCloudClientBuilderFinalStep UseContactPoint(string contactPoint, bool forceSsl = true);`

Thanks!

**Comment by Zelldon** [comment]
Hey @ShawnAbshire thanks for using the C# client. If you don't use Camunda Cloud then please use the normal ZeebeClient builder, see as example here https://github.com/camunda-community-hub/zeebe-client-csharp/blob/main/Client.Examples/Program.cs#L39-L44

I will close this issue since this is already possible. Feel free to reopen if you think otherwise.

**Comment by ShawnAbshire** [comment]
I had overlooked this Zelldon, Thanks for your response, will try it out Monday!
