### ISSUE TITLE
I can use the client to set **local** variables when sending a CompleteJobCommand

### ISSUE THREAD

**Issue by vavans** [camunda-community-hub/zeebe-client-csharp#468]
When i handle a task in a worker, i would like to set local variables to the task as described in the Camunda API:
https://docs.camunda.org/manual/latest/reference/rest/external-task/post-complete/#request-body

see `localVariables`

For now, i managed to set a process scope variable, using the `Variables` function
```csharp
async Task HandleJob(IJobClient jobClient, IJob job)
{
    // do some work
    var output = ...

    jobClient    
    .NewCompleteJobCommand(job)
    .Variables(JsonSerializer.Serialize(output))
    .Send();
}
```

I would like an API like:
```csharp
async Task HandleJob(IJobClient jobClient, IJob job)
{
    // do some work
    var output = ...

    jobClient    
    .NewCompleteJobCommand(job)
    .LocalVariables(JsonSerializer.Serialize(output))  //here, using some kind of LocalVariables function
    .Send();
}
```

Am i missing someting ?

Thanks
Julien

**Comment by Zelldon** [comment]
Hey @vavans 

the referenced documentation is for Camunda 7, whereas the .net client you try to use is for Camunda 8 and doesn't support that. Here is the related Camunda 8 doc for handling jobs https://docs.camunda.io/docs/components/concepts/job-workers/#requesting-jobs Since Zeebe the process engine behind Camunda 8, doesn't support this yet I will close this issue. Feel free to open an issue here https://github.com/camunda/zeebe

Workaround:

As workaround you can either create the variable as input mapping when the scope is created (e.g. on a sub process or on the task it self). Or you use the `setVariable` RPC and use an element instance key, to set the variable to a local scope.

Greets
Chris
